### ISSUE TITLE
Doesn't install in Visual Studio 2019

### ISSUE THREAD

**Issue by MartinHT** [TargetFrameworkMigrator/TargetFrameworkMigrator#58]
Doesn't install in VS2019. Fails to install with the error saying references are missing to Microsoft.VisualStudio.Component.VSSDK. Visual Studio extension development workload is fully installed though.

**Comment by xt0rted** [comment]
Just ran into this as well. From the install log:

```
4/9/2019 12:49:18 AM - Beginning to install extension to Microsoft Visual Studio Professional 2019...
4/9/2019 12:49:19 AM - Install Error : Microsoft.VisualStudio.ExtensionManager.MissingReferencesException: This extension cannot be installed because the following references are missing:
-Microsoft.VisualStudio.Component.VSSDK (Microsoft.VisualStudio.Component.VSSDK)
   at Microsoft.VisualStudio.ExtensionManager.EngineUtilities.EnsureNoMissingReferences(IEnumerable`1 missingRefs)
   at Microsoft.VisualStudio.ExtensionManager.PackageInstaller.PrepareEngineInstall(IDependencyGraph dGraph, IDependencyComparisonSeed seed, Component vsCompPkg, Boolean isProductComponent, Int32& totalInstallationSteps)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.PerformSetupEngineInstall(InstallableExtensionImpl extension, Boolean installPerMachine, Boolean isPackComponent, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, IProgress`1 progress, InstallFlags installFlags, AsyncOperation asyncOp, Version targetedVsVersion, IInstalledExtension& newExtension)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallInternal(InstallableExtensionImpl extension, InstallFlags installFlags, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, IProgress`1 progress, Version targetedVsVersion)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.BeginInstall(IInstallableExtension installableExtension, InstallFlags installFlags, AsyncOperation asyncOp, Version targetedVsVersion)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallWorker(IInstallableExtension extension, InstallFlags installFlags, AsyncOperation asyncOp)
```

**Comment by tchivs** [comment]
me too

**Comment by flashbackjon** [comment]
I'm having this same issue:

`5/13/2019 11:01:07 AM - Beginning to install extension to Microsoft Visual Studio Professional 2019...
5/13/2019 11:01:08 AM - Install Error : Microsoft.VisualStudio.ExtensionManager.MissingReferencesException: This extension cannot be installed because the following references are missing:
-Microsoft.VisualStudio.Component.VSSDK (Microsoft.VisualStudio.Component.VSSDK)
   at Microsoft.VisualStudio.ExtensionManager.EngineUtilities.EnsureNoMissingReferences(IEnumerable`1 missingRefs)
   at Microsoft.VisualStudio.ExtensionManager.PackageInstaller.PrepareEngineInstall(IDependencyGraph dGraph, IDependencyComparisonSeed seed, Component vsCompPkg, Boolean isProductComponent, Int32& totalInstallationSteps)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.PerformSetupEngineInstall(InstallableExtensionImpl extension, Boolean installPerMachine, Boolean isPackComponent, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, IProgress`1 progress, InstallFlags installFlags, AsyncOperation asyncOp, Version targetedVsVersion, IInstalledExtension& newExtension)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallInternal(InstallableExtensionImpl extension, InstallFlags installFlags, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, IProgress`1 progress, Version targetedVsVersion)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.BeginInstall(IInstallableExtension installableExtension, InstallFlags installFlags, AsyncOperation asyncOp, Version targetedVsVersion)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallWorker(IInstallableExtension extension, InstallFlags installFlags, AsyncOperation asyncOp)
`

**Comment by wollmich** [comment]
Please add support for Visual Studio 2019.

**Comment by haakoo** [comment]
I'm getting the same problem. I installed the `Visual Studio SDK` workload and then I get the following error message in the log: 

```log
06.08.2019 12:59:55 - Searching for applicable products...
06.08.2019 12:59:55 - Found installed product - Global Location
06.08.2019 12:59:55 - Found installed product - Visual Studio Enterprise 2019 Preview
06.08.2019 12:59:55 - Found installed product - Visual Studio Enterprise 2019
06.08.2019 12:59:55 - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(IInstallableExtension extension, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by ESimmonds** [comment]
VS2019 Installation Target needs to be defined as the upper bound. 18 instead of 16 then account for breaking changes

https://github.com/VHQLabs/TargetFrameworkMigrator/blob/master/TargetFrameworkMigratorVSIX/source.extension.vsixmanifest
```
<InstallationTarget Version="[15.0,18.0)" Id="Microsoft.VisualStudio.Community" />
<InstallationTarget Version="[15.0,18.0)" Id="Microsoft.VisualStudio.Enterprise" />

<Prerequisite Id="Microsoft.VisualStudio.Component.VSSDK" Version="[15.0.26208.0,18.0)" DisplayName="Visual Studio SDK" />
```

**Comment by tomaustin700** [comment]
Still waiting for this, is this planned at all?

**Comment by djseng** [comment]
Was able to get up an running using the release on this fork https://github.com/Ian1971/TargetFrameworkMigrator/releases

**Comment by 304NotModified** [comment]
This will be fixed in the next release. Thanks for your patience!

**Comment by ESimmonds** [comment]
Thanks @304NotModified
